run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gocyclo
    - revive
    - govet
    - errcheck
    - ineffassign
    - staticcheck

linters-settings:
  gocyclo:
    min-complexity: 10

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
